name: CI
on: [push]
jobs:
    build:
        runs-on: ubuntu-latest
        container: gableroux/unity3d:2020.1.1f1
        environment: env
        steps:
            - name: Checkout Project
              uses: actions/checkout@v2
              with:
                submodules: recursive
                
            - name: Decrypt License
              run: openssl aes-256-cbc -d -pbkdf2 -in .github/Unity_v2020.x.ulf.enc -k ${{ secrets.UNITY_LICENSE_DECRYPT_KEY }} >> .github/Unity_v2020.x.ulf
            
            - name: Activate Unity
              run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .github/Unity_v2020.x.ulf || exit 0
            
            - name: Build Windows Player
              run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -buildWindows64Player ./bin-win64/jotr.exe
            - name: Build OSX Player
              run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -buildOSXUniversalPlayer ./bin-osx/jotr.app
            
            - name: Archive Windows Build
              uses: actions/upload-artifact@v1
              with:
                name: jotr_win
                path: ./bin-win64
                
            - name: Archive Mac Build
              uses: actions/upload-artifact@v1
              with:
                name: jotr_osx
                path: ./bin-osx
